#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # create analyzer instance
    analyzer = Analyzer(positives, negatives)

    # get user timeline        
    tweets = get_user_timeline(sys.argv[1], 50)
    
    # error if timeline not successfully returned
    if tweets == None:
        sys.exit("Unable to retrieve user tweets")

    for t in tweets:
        # compute score
        score = analyzer.analyze(t)
        
        # print and colorize score, emoji
        if score > 0.0:
            print(colored(str(score) + ":)", "green"))
        elif score < 0.0:
            print(colored(str(score) + ":(", "red"))
        else:
            print(colored(str(score) + ":|", "yellow"))


if __name__ == "__main__":
    main()

